// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZwTz-z9refRmTXv6N9PzPusloI_lwko',
    appId: '1:450399040998:android:5a82b22579c9a273d35227',
    messagingSenderId: '450399040998',
    projectId: 'fibrechat-fcd22',
    databaseURL: 'https://fibrechat-fcd22-default-rtdb.firebaseio.com',
    storageBucket: 'fibrechat-fcd22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpnQWyFOntt9LkwRb590FxUu3X6HzsbPs',
    appId: '1:450399040998:ios:ad6376335925f7ced35227',
    messagingSenderId: '450399040998',
    projectId: 'fibrechat-fcd22',
    databaseURL: 'https://fibrechat-fcd22-default-rtdb.firebaseio.com',
    storageBucket: 'fibrechat-fcd22.appspot.com',
    androidClientId: '450399040998-2fpujoup8v6fsn6cucmr94tkdgnosme2.apps.googleusercontent.com',
    iosClientId: '450399040998-ja58ue1jpajs7eg64tq9gtnqkqq9f2lj.apps.googleusercontent.com',
    iosBundleId: 'com.vazra.apps',
  );
}
